version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  Before Install:
    - location: stop.bash
      timeout: 300
  After Install:
    - location: start.bash
      timeout: 300	
