version: '3'
services:
  test: 
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=admin
    volumes: 
      - /root:/opt/amar
  jenkins:
    image: jenkins
    ports:
      - "8080:8080"
    environment:
      - a=10
    volumes:
      - /root:/opt/reddy
    depends_on:
      - test
      
      
networks:
  - testing
  
